version: '2'
services:
  default:
    links:
      - db:db
    ports:
      - 3000:3000
  db:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: deductions_user
      POSTGRES_DB: deductions_test
      LC_ALL: C
    ports:
      - 5432:5432